// File generated by Antigravity manually based on provided google-services.json
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF8QWi4QR0IXyJWzkkgURkUzFyKtTVjQ8',
    appId: '1:706769547838:web:placeholder', // Placeholder - Web Support requires running `flutterfire configure`
    messagingSenderId: '706769547838',
    projectId: 'attendence-apps10',
    authDomain: 'attendence-apps10.firebaseapp.com',
    storageBucket: 'attendence-apps10.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF8QWi4QR0IXyJWzkkgURkUzFyKtTVjQ8',
    appId: '1:706769547838:android:2f83921265ed1a6a22d76f',
    messagingSenderId: '706769547838',
    projectId: 'attendence-apps10',
    storageBucket: 'attendence-apps10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF8QWi4QR0IXyJWzkkgURkUzFyKtTVjQ8',
    appId: '1:706769547838:ios:placeholder', // Placeholder
    messagingSenderId: '706769547838',
    projectId: 'attendence-apps10',
    storageBucket: 'attendence-apps10.firebasestorage.app',
    iosBundleId: 'com.attendence',
  );
  
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF8QWi4QR0IXyJWzkkgURkUzFyKtTVjQ8',
    appId: '1:706769547838:ios:placeholder', // Placeholder
    messagingSenderId: '706769547838',
    projectId: 'attendence-apps10',
    storageBucket: 'attendence-apps10.firebasestorage.app',
    iosBundleId: 'com.attendence',
  );
}
